### ISSUE TITLE
How to delete a storage after function executed

### ISSUE THREAD

**Issue by besnikh** [SeregPie/VueStorage#3]
Hi,
This is something I was looking to, actually you made something much better than I was looking for.

In my case, when user is submitting a form, I want to store it's form values so if the user decides to leave the form and come back later he will be able to see what he already wrote. 

But, how can I do it that after a submit button is pressed, and a POST request is sent to my backend the Storage needs to be cleared for that key. 

I am using as a key an unique form id which will be auto generated every time a user starts submitting a form. 

Looking forward to get some help in this case :) 

Cheers

**Comment by SeregPie** [comment]
Hello.
The stored value will be deleted, if you set the value to `null` or `undefined`.
See [here](https://github.com/SeregPie/VueStorage/blob/master/src/members/ReactiveStorage.js#L81).

You can write something like this.
```js
stored() {
  formData: {/*...*/},
}
/*...*/
async submit() {
  await httpSend(this.formData);
  this.formData = null;
}
```

**Comment by SeregPie** [comment]
Why must the key be auto generated every time? Why not just set it to something like `forms/<action>/data`?
